### PR TITLE
added wind directions for darksky

### PR DESCRIPTION
**Pull request by viserion**
instead of displaying the "degree" numbers, wind directions for DE, EN, FR and NL languages are added
additionally the display of the weatherdata in the widget are moved

### CODE REVIEW

**Comment by smartVISU-newstuff** [comment]
Thanks for the contribution. I have published the update on https://github.com/smartVISU-newstuff/widgets/tree/master/darksy and in the forum for extended testing by the users.
It is planned to integrate this PR into the next major release ov smartVISU.

**Comment by psilo909** [comment]
why is this folder called "darksy" and not "darksky"?

**Comment by wvhn** [comment]
Ups.  Maybe I shouldn’t do such things after midnight. I’ll fix it during the day

**Comment by wvhn** [comment]
Done: https://github.com/smartVISU-newstuff/widgets/tree/master/darksky

**Pull request merged**
