### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by AZAZ78**
Added alternative wunderground adapter with free access which ist also used by wunderground enabled weather Stations.
The Public Key is 6532d6454b8aa370768e63d6ba5a832e

### CODE REVIEW

**Comment by wvhn** [comment]
Thanks for the contribution. I've downloaded the code, test it locally and integrate it into my changes on the weather widgets. 
Uploaded it also to smartvisu-newstuff repo. 
Will merge it asap.

**Comment by wvhn** [comment]
Test results are OK so far. I had to find out the configuration parameters, first. 
Since the service runs only with a weather station ID, I'll provide the code permanently on https://github.com/smartVISU-newstuff/widgets/tree/master/weather.com but not merge it as standard into SV.

**Comment by AZAZ78** [comment]
Hi,

thanks for including. Sorry that i had not provided a test configuration.
As far as i can see the standard wunderground plugin is not working any
more (at least for me) because they removed the API access. In the first
step i thought of completely replacing it ...

What is the difference between this code and the standard wunderground lib?
There i also need a key and a weather station id?

Do you have an hint how to access the code if it is not part of the default
code?

Thanks
Alex

Am Mo., 9. Nov. 2020 um 23:48 Uhr schrieb wvhn <notifications@github.com>:

**Comment by wvhn** [comment]
Are you a member in knx-user-forum.de? Or on gitter? You could write me a PN there in order to facilitate the communication.
My user id from here is also valid in the forum.

Since the wunderground service seems to be broken in smartVISU we could establish your weather.com adapter as a standard. To do this, I need some more information.

**Pull request closed without merging**
