### PR TITLE
Fix examples

### PR DESCRIPTION
**Pull request by i-am-offline**
Mainly replaced PNG by SVG images

### CODE REVIEW

**Comment by i-am-offline** [comment]
PR contains unwanted commits. Will fix this immediately ....

**Comment by i-am-offline** [comment]
Fixed

**Comment by smaiLee** [comment]
I don't see any reason to not merge this.
We still can delete it if we decide to completely remove all examples.

Please merge it yourself if no one disagrees in the next few days.

**Comment by i-am-offline** [comment]
OK, I'll merge this in the next days, but before merging I will use it to add the fixes for the other example pages as well.

**Pull request merged**
