### PR TITLE
Add Configurable Snow

### PR DESCRIPTION
**Pull request by Bonze255**
My First Pull Request to add Configurable Snow in Visu

### CODE REVIEW

**Comment by Bonze255** [comment]
sry also add this between <body></bod<>in root.html:
<script type="text/javascript">
    $(document).ready( function(){
    	$.fn.snow({ minSize: 5, maxSize: 50, newOn: 1000, flakeColor: '#0099FF' });
    });
</script>

**Comment by smaiLee** [comment]
Thank you for your contribution.

I'm sorry to have some improvement proposals:
1. The $.fn.snow... in root html should be conditioned to config_snow
1. The config.php should not be part of the PR as this is the personal configuration file. Default configuration is placed in /lib/defaults.php
1. Please make PR to develop branch. Caution: Because of the recent jQm update the flipswitches in config.html have to be of type flipswitch insteadof slider.

**Comment by Bonze255** [comment]
is it useful? i dont know to change the branch to "develop"..

**Comment by ThomasCr** [comment]
git checkout -b develop

**Comment by onkelandy** [comment]
Sounds cool.. Any chance to get included @smaiLee ?

**Comment by wvhn** [comment]
This does not run on smartVISU v2.9 due to the changed configuration structure.
An adaption has been made an will be provided on github on smartvisu-newstuff/modding

**Pull request closed without merging**
