### PR TITLE
sh.py: try to convert count value to integer if possible

### PR DESCRIPTION
**Pull request by robertaistleitner**
smarthome.py expects count to be an integer value which is not the case at the moment

### CODE REVIEW

**Comment by msinn** [comment]
Could you explain the reason for this modification?

**Comment by psilo909** [comment]
i just added an "alert(pt[pt.length - 1]);" in the else part and am always getting numbers (integers).

@robertaistleitner : pls explain in which setting this seems to be problematic for you

**Comment by robertaistleitner** [comment]
Here I'm getting strings as count:
image

It's kind of weird because it obviously happens only when I'm accessing the subpage `index.php?page=room_wohnbereich` directly. If I'm navigating there from the root page it works...

I also get this exception on load if accessing directly:
image

If I'm coming from the root page, the count isn't sent at all in my case:
image

Maybe I misconfigured something or does this happen to someone else as well?

Note: I'm on current development branch.

**Comment by smaiLee** [comment]
Could it be that there was something old in your browser cache?
In previous version there was no count, so an old file in cache would explain the mussing count.
Would you re-test with current develop branch?

**Comment by smaiLee** [comment]
I close this as it seems not to be necessary.

**Pull request closed without merging**
