### PR TITLE
lang and notify updates

### PR DESCRIPTION
**Pull request by gruberth**
- Added italian language file
- Added langugage translation in configuration page notifys (clear cache, save config, shng driver error)
- Changed definition format of backup entries in lang files
- Changed handling of the success notify after configuration save, because the notify message was always lost after the page reload

### CODE REVIEW

**Comment by gruberth** [comment]
Last commit needs review.

Works only on Desktop. On mobile the message does not get shown on reload. You need to change the page first and then return to the config page to trigger the page create and the show notify.

**Comment by wvhn** [comment]
I reverted the last commit for the time being because the function did not work correctly on some of my mobile devices. I'll keep working on it. We need to delete the success message as soon as the users changes a configuration setting (or after some seconds delay).

**Comment by wvhn** [comment]
@gruberth i have pushed a new version of the notify after config sve. It works with all my mobiles now.
The message is now bound to the jQm event "pagecontainerbeforeshow" and disappears within 10 seconds after reload.
Tests welcome and thanks for the idea.

E grazie tante per la traduzione in Italiano!

**Comment by gruberth** [comment]
Hi, finally had time to test it. Works on every device!

;)

**Pull request merged**
