### PR TITLE
new feature in Config - widget constructor

### PR DESCRIPTION
**Pull request by Andrek01**
Hopefully i forgot nothing, explanation on knx-user-forum

best regards 

Andre

### CODE REVIEW

**Comment by onkelandy** [comment]
Thanks alot!
I got the following problems:
- codemirror files missing. Downloaded v5.52.2 manually, works. However not all files seem to be necessary. 
- the line number in the widget constructor is displayed as overlay and therefore covering up the widget text
- using a dynamic icon within a widget makes problems
- colours should be auto-put into '...'
- defining "icon0" as color shouldn't bring up the icon dropdown

**Comment by Andrek01** [comment]
"Merde" i forgot the codemirror dir do upload.

New pull with correct versionof codemirror. This is the version that is used in shNG.
Development was based on this version.

best regards

**Comment by Andrek01** [comment]
Added " import quad.html as quad" in template for rendering - i forgot it :-(
Added preview for icons in tooltip-window
Added new dictionary for color (CTRL+5) including icon0/icon1
Added preview for colors in tooltip-window(icon0/icon1 has no preview right now)

**Comment by wvhn** [comment]
I have moved some files within the folder structure and changed the include / script statements accordingly in my local git. The changed version is now part of the actual smartvisu/develop version.

**Pull request closed without merging**
